### ISSUE TITLE
Wrong header copied to EFFVAR extension in datacube

### ISSUE THREAD

**Issue by Knusper** [astrobellatrix/muse-functions#1]
https://github.com/astrobellatrix/muse-functions/blob/4da38e7de4587a32f8cc82c557b584b2edd17a72/create_cubes.py#L147C13-L147C86

Use 'ihdu_v" in this line, instead of 'ihdu_d' ...  Otherwise units of EFFVAR are wrong.

**Comment by astrobellatrix** [comment]
Good catch, it was indeed an error on my side!
